import requests
import time
import sys

BASE_URL = 'http://127.0.0.1:5173'

def log(step, title, msg=""):
    print(f"\n[{step}] {title}")
    if msg:
        print(f"    {msg}")

def run():
    print("=" * 70)
    print("   HN-AI-05 CROSS-HOSPITAL RESOURCE REBALANCER - LIVE DEMO RUN")
    print("   Connecting to Frontend & Backend via:", BASE_URL)
    print("=" * 70)

    # 1. Health & Database Check
    log("STEP 1", "SYSTEM HEALTH CHECK")
    res = requests.get(f"{BASE_URL}/health")
    assert res.status_code == 200, f"Health check failed: {res.text}"
    health = res.json()
    db_info = health.get("database", {})
    print(f"    System Status : {health.get('status')}")
    print(f"    Database Mode : {db_info.get('status_text')} ({db_info.get('provider')})")
    print(f"    Active Database: {db_info.get('database')}")
    print(f"    Total Collections: {len(db_info.get('collections', {}))}")

    # 2. Reset Simulation Baseline
    log("STEP 2", "RESETTING TO DETERMINISTIC BASELINE")
    res = requests.post(f"{BASE_URL}/api/simulation/reset")
    assert res.status_code == 200
    state = requests.get(f"{BASE_URL}/api/state").json()
    print("    Baseline Hospitals Stock:")
    for h in state["hospitals"]:
        print(f"      - {h['name']} ({h['id']}): Stock = {h['current_stock']} | Safety Threshold = {h['safety_threshold']}")

    # 3. Start Simulation
    log("STEP 3", "STARTING LIVE SIMULATION")
    res = requests.post(f"{BASE_URL}/api/simulation/start")
    assert res.status_code == 200
    print("    Simulation loop started. 3-second tick interval.")

    # 4. Inject Surge on District Hospital A
    log("STEP 4", "INJECTING SURGE ON DISTRICT HOSPITAL A (H-A)")
    res = requests.post(f"{BASE_URL}/api/simulation/surge")
    assert res.status_code == 200
    print("    Surge successfully injected! Demand consumption rate multiplied.")

    # 5. Monitor Live Depletion and Predictive Alert
    log("STEP 5", "MONITORING PREDICTIVE SHORTAGE DETECTION")
    print("    Waiting for sensor readings to process...")
    for i in range(8):
        time.sleep(3.2)
        state = requests.get(f"{BASE_URL}/api/state").json()
        h_a = next(h for h in state["hospitals"] if h["id"] == "H-A")
        pred_a = next(p for p in state["predictions"] if p["hospital_id"] == "H-A")
        recs = [r for r in state["recommendations"] if r.get("status") == "pending"]
        print(f"    [Tick {state['simulation']['tick']}] H-A Stock: {h_a['current_stock']} | Burn Rate: {pred_a.get('depletion_rate')} u/hr | Shortage in: {pred_a.get('time_to_shortage_hours')}h | Status: {pred_a.get('status')}")
        if pred_a.get("status") == "CRITICAL" or len(recs) > 0:
            break

    # 6. Check Recommendation Generated by Python Optimizer
    log("STEP 6", "DETERMINISTIC TRANSFER RECOMMENDATION")
    recs = [r for r in state["recommendations"] if r.get("status") == "pending"]
    assert len(recs) > 0, "No pending recommendation generated!"
    rec = recs[0]
    print(f"    Recommendation ID : {rec['id']}")
    print(f"    Source (Donor)    : {rec['from_hospital']}")
    print(f"    Recipient         : {rec['to_hospital']}")
    print(f"    Quantity          : {rec['quantity']} cylinders")
    print(f"    Dispatch Deadline : Within {rec['dispatch_deadline_minutes']} minutes")
    print(f"    Donor Safety Margin After Transfer: {rec.get('donor_safety_margin_after', 'Verified')} cylinders")
    print(f"    Winning Rationale : {rec.get('winning_reason')}")
    print(f"\n    Gemini Operational Explanation:\n    \"{rec.get('justification')}\"")

    # 7. Check Operations Copilot Action
    log("STEP 7", "GEMINI OPERATIONS COPILOT BRIEFING")
    copilot_payload = {
        "action_type": "incident_brief",
        "facts": {
            "critical_hospital": "District Hospital A",
            "time_to_shortage": "1.3 hours",
            "donor_hospital": "District Hospital B",
            "transfer_quantity": 40,
            "donor_surplus": 84,
            "transit_minutes": 20
        }
    }
    copilot_res = requests.post(f"{BASE_URL}/api/copilot/action", json=copilot_payload)
    if copilot_res.status_code == 200:
        copilot_data = copilot_res.json()
        print(f"    Incident Commander Brief: {copilot_data.get('content')}")

    # 8. Human-in-the-Loop Approval
    log("STEP 8", "HUMAN APPROVAL OF TRANSFER")
    appr_res = requests.post(f"{BASE_URL}/api/recommendations/{rec['id']}/approve")
    assert appr_res.status_code == 200
    appr_data = appr_res.json()
    h_a_after = next(h for h in appr_data["state"]["hospitals"] if h["id"] == "H-A")
    h_b_after = next(h for h in appr_data["state"]["hospitals"] if h["id"] == "H-B")
    print(f"    Transfer Approved & Executed!")
    print(f"    Recipient H-A Stock: {h_a_after['current_stock']} (+40 cylinders added)")
    print(f"    Donor H-B Stock    : {h_b_after['current_stock']} (-40 cylinders transferred)")
    print(f"    Donor Safety Check : H-B Stock {h_b_after['current_stock']} >= Threshold {h_b_after['safety_threshold']} (SAFE)")
    print(f"    Shortage-Hours Prevented: {appr_data['state']['metrics']['shortage_hours_prevented']} hours")

    # 9. What-If Scenario Simulator
    log("STEP 9", "WHAT-IF COUNTERFACTUAL STRESS TEST")
    whatif_res = requests.post(f"{BASE_URL}/api/scenario/simulate", json={"scenario_type": "demand_plus_20"})
    if whatif_res.status_code == 200:
        whatif = whatif_res.json()
        print(f"    Stress Scenario: {whatif.get('scenario_name')}")
        print(f"    Summary: {whatif.get('summary')}")
        print(f"    Shortage Hours Prevented: {whatif.get('shortage_hours_prevented')} hours")

    # 10. Counterfactual Replay
    log("STEP 10", "COUNTERFACTUAL REPLAY EVALUATION")
    replay_res = requests.get(f"{BASE_URL}/api/replay")
    assert replay_res.status_code == 200
    replay = replay_res.json()
    print(f"    Without System Shortage: {replay['without_system']['shortage_hours']} hours")
    print(f"    With System Shortage   : {replay['with_system']['shortage_hours']} hours")
    print(f"    Net Hours Prevented    : {replay['shortage_hours_prevented']} hours")
    print(f"    Donor Safety Maintained: {replay['donor_safety_maintained']}")
    print(f"    Secondary Shortages    : {replay['secondary_shortages_created']}")

    # 11. Held-Out Model Evaluation
    log("STEP 11", "HELD-OUT NUMERICAL EVALUATION")
    eval_res = requests.get(f"{BASE_URL}/api/evaluation")
    assert eval_res.status_code == 200
    evaluation = eval_res.json()
    print(f"    Linear Trend Model MAE  : {evaluation['model_mae']} cylinders")
    print(f"    Naive Baseline MAE      : {evaluation['baseline_mae']} cylinders")
    print(f"    Relative Improvement   : +{evaluation['relative_improvement_pct']}% error reduction")

    # 12. Decision Audit Trail
    log("STEP 12", "DECISION AUDIT TRAIL VERIFICATION")
    audit_res = requests.get(f"{BASE_URL}/api/audit")
    if audit_res.status_code == 200:
        audit_records = audit_res.json().get("audit_trail", [])
        print(f"    Total Audit Events Logged: {len(audit_records)}")
        print("    Recent Events:")
        for ev in audit_records[-4:]:
            print(f"      [{ev.get('timestamp')[:19]}] {ev.get('event_type')}: ID={ev.get('id')}")

    print("\n" + "=" * 70)
    print("   ALL STEPS COMPLETED AND VERIFIED ON LIVE RUNNING APPLICATION!")
    print("=" * 70)

if __name__ == "__main__":
    run()
